### ISSUE TITLE
Control commands from code

### ISSUE THREAD

**Issue by carlo98** [hyper750/eachine-e511s#1]
Hi, great work! I was wondering if you are also planning to work on sending commands to the drone  😀 because I'd like to try to insert a few autonomous features

**Comment by hyper750** [comment]
Thanks a lot, I appreciate it. Well, my plan was the following.
1. Receive telemetry data (Done)
2. Receive video frames (WIP)
3. Send commands to the drone (Not done)

The drone was not mine and I have had to return it to the owner, so I can't continue the reverse engineering :sweat_smile:.

**Comment by carlo98** [comment]
Ok💪 then I'll try to do that and, if successful, write you! Can't wait to see the frames😉
